name: iosagent
options:
  bundleIdPrefix: com.welsonslee
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGNING_ALLOWED: "NO"
    ENABLE_BITCODE: "NO"
    SWIFT_VERSION: "5.0"

targets:
  iosagent:
    type: application
    platform: iOS
    sources:
      - path: iosagent
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.welsonslee.iosagent.dev
        INFOPLIST_FILE: iosagent/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        DEVELOPMENT_TEAM: ""
        ENABLE_USER_SCRIPT_SANDBOXING: "NO"
